export const ADD_POPULAR_MOVIES = "ADD_POPULAR_MOVIES";
export const ADD_LATES_MOVIES = "ADD_LATES_MOVIES";
export const SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE";
export const ADD_SIMILAR_MOVIES = "ADD_SIMILAR_MOVIES";